from faker import Faker

faker = Faker("zh_CN")
address = faker.address()
building_number = faker.building_number()
city = faker.city()
cityname = faker.city_name()
city_suf = faker.city_suffix()
country = faker.country()
country_2 = faker.country_code(representation="alpha-2")
district = faker.district()
postcode = faker.postcode()
province = faker.province()
street_address = faker.street_address()
street_name = faker.street_name()
street_suffix = faker.street_suffix()

print("address:", address)
print("building_number:", building_number)
print("city:", city)
print("cityname:", cityname)
print("city_suf:", city_suf)
print("country:", country)
print("country_2:", country_2)
print("district:", district)
print("postcode:", postcode)
print("province:", province)
print("street_address:", street_address)
print("street_name:", street_name)
print("street_suffix:", street_suffix)
